### ISSUE TITLE
NameError: name 'server' is not defined

### ISSUE THREAD

**Issue by rohanday3** [mudpi/installer#2]
Hi, I've just installed raspbian on a fresh sd card and installed mudpi using the curl command, i then tried to create the config file with the config file creator on the website but it seems it is no longer supported, so i did it the normal way, with the example config and changed it around to my needs. When i tried to start mudpi.py however, it ran into some issues

my config:

{
    "name": "TheUnreactiveMudPi",
    "version": 0.8,
    "debug": false,
    "redis": {
        "host": "127.0.0.1",
        "port": 6739
    },
    "relays": [
        {
            "pin": "4",
            "normally_open": true,
            "group": "1",
            "name": "Water",
            "topic": "garden/pi/relays/1",
            "key": "relay_1"
        }
    ],
    "server": {
        "host": "127.0.0.1",
        "port": 6602
    },
    "workers": [
	{
	    "type": "sensor",
	    "sensors": []
	}
    ],
    "nodes": [
        {
            "name": "Arduino",
            "address": "/dev/ttyUSB0",
            "type": "arduino",
            "use_wifi": false,
            "sensors": [
                {
                    "pin": "7",
                    "is_digital": true,
                    "type": "Temperature",
                    "name": "Temperature1"
                },
                {
                    "pin": "6",
                    "is_digital": true,
                    "type": "Temperature",
                    "name": "Temperature2"
                },
                {
                    "pin": "5",
                    "is_digital": true,
                    "type": "Temperature",
                    "name": "Temperature3"
                },
                {
                    "pin": "A0",
                    "is_digital": false,
                    "type": "Soil",
                    "name": "Moisture1"
                },
                {
                    "pin": "A1",
                    "is_digital": false,
                    "type": "Soil",
                    "name": "Moisture"
                }
            ]
        }
    ]
}

error:

 __  __           _ _____ _
|  \/  |         | |  __ (_)
| \  / |_   _  __| | |__) |
| |\/| | | | |/ _` |  ___/ |
| |  | | |_| | (_| | |   | |
|_|  |_|\__,_|\__,_|_|   |_|
_________________________________________________

Eric Davisson @theDavisson
Version:  0.8

Initializing Garden Control...           Complete
Preparing Threads for Workers...         Complete
No Camera Found to Load
Loading Pi Sensor Worker...
Pi Sensor Worker [2 Sensors]...          Running
Relay Worker relay_1...                  Ready
Relay Worker relay_1...                  Running
[Arduino] Serial Connection      Success
Invalid or no Nodes found to Load
Traceback (most recent call last):
  File "mudpi.py", line 171, in <module>
    t = ArduinoWorker(node, main_thread_running, system_ready)
  File "/etc/mudpi/core/workers/arduino_worker.py", line 34, in __init__
    if self.config['controls'] is not None:
KeyError: 'controls'
No Actions Found to Load
Traceback (most recent call last):
  File "mudpi.py", line 191, in <module>
    for action in CONFIGS["actions"]:
KeyError: 'actions'
No Triggers Found to Load
Traceback (most recent call last):
  File "mudpi.py", line 201, in <module>
    t = TriggerWorker(CONFIGS['triggers'], main_thread_running, system_ready, actions)
KeyError: 'triggers'
MudPi Shutting Down...                   Starting
Traceback (most recent call last):
  File "/etc/mudpi/core/server/mudpi_server.py", line 20, in __init__
    self.sock.bind((self.host, self.port))
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mudpi.py", line 216, in <module>
    server = MudpiServer(main_thread_running, CONFIGS['server']['host'], CONFIGS['server']['port'])
  File "/etc/mudpi/core/server/mudpi_server.py", line 22, in __init__
    print('Failed to create socket. Error Code: ', str(msg[0]), ' , Error Message: ', msg[1])
TypeError: 'OSError' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mudpi.py", line 247, in <module>
    server.sock.shutdown(socket.SHUT_RDWR)
NameError: name 'server' is not defined
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by olixr** [comment]
Did you try running in debug mode for better logging? That is always a great first step to figuring out what is wrong in your setup. 

Your error log says `OSError: [Errno 98] Address already in use` which means you should maybe change the server `port`. Usually the output will tell you where to start debugging more. 

Also when you post a long log try to use the code format (put code text between two triple ```) to make things easier to digest for the supporters. 

Please let me know what you are able to find out and we will close this issue.

**Comment by rohanday3** [comment]
I Will try this today and let you know.

**Comment by olixr** [comment]
Have you any updates on this issue? If not I will move to close it soon.

**Comment by rohanday3** [comment]
Yes, you may want to put it in the help section. I had used the installer
and what actually happened was mudpi was running already because of that
process manager that comes with it. So the server could not be created
since it was already running and thus the port was being used even though
it was a fresh install.
