### ISSUE TITLE
Installer doesn't seem to install phpredis extension

### ISSUE THREAD

**Issue by Vertikar** [mudpi/installer#3]
After installing mudpi using installer, initial pages of UI work, but dashboard.php throws a HTTP 500 error.
Issue is viewable in nginx error logs:

```2020/09/16 03:41:09 [error] 622#622: *18 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /var/www/html/mudpi/app/dashboard.php:27
Stack trace:
#0 {main}
  thrown in /var/www/html/mudpi/app/dashboard.php on line 27" while reading response header from upstream, client: 192.168.x.x, server: _, request: "GET /dashboard.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "hostname"
2020/09/16 03:41:10 [error] 622#622: *18 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /var/www/html/mudpi/app/dashboard.php:27
Stack trace:
#0 {main}
  thrown in /var/www/html/mudpi/app/dashboard.php on line 27" while reading response header from upstream, client: 192.168.x.x, server: _, request: "GET /dashboard.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "hostname"``

**Comment by olixr** [comment]
Was issue with Redis not being linked to PHP. i.e. php-redis. Should be fixed in latest updates. 

Also working on update to make installer ready for v0.10.0

**Comment by bpjobin** [comment]
I'm having the same output from the nginx error.log file. I made a php-version.php page that outputs phpinfo() and I can see that php7.3 is being used and that the redis package along side others are being loaded. I've restarted the php and nginx services to no avail. Using a pi 2 b+ with raspbian buster 10. Is there anything I can do to debug further?

Thank you
