### ISSUE TITLE
Default Logger log file location doesn't have permissions to write to directory

### ISSUE THREAD

**Issue by icyspace** [mudpi/installer#7]
The installer does not grant proper permissions to the default mudpi.log directory.  this can be corrected after the installer runs granting the www-data group write access to the mudpi core dir. 

`sudo chmod g+w /etc/mudpi/core`

Error when trying to run with default logging 

Traceback (most recent call last):
  File "mudpi.py", line 92, in <module>
    Logger.logger = Logger(CONFIGS)
  File "/etc/mudpi/core/logger/Logger.py", line 45, in init
    open(logger_config['file'], 'w').close()  # testing file path
PermissionError: [Errno 13] Permission denied: 'mudpi.log'

**Comment by olixr** [comment]
The installer now sets default permissions as of https://github.com/mudpi/installer/commit/6c04b312f18762bc7ec3ca90d5381b84ea749169

This is also updated to install v0.10.0 + now
