### ISSUE TITLE
/etc/hosts questions

### ISSUE THREAD

**Issue by SecT0uch** [mudpi/installer#9]
What is the purpose of adding these lines to `/etc/hosts` ?:
```
10.45.12.1	clients3.google.com #MUDPI-captiveportal
10.45.12.1	clients.l.google.com #MUDPI-captiveportal
10.45.12.1	connectivitycheck.android.com #MUDPI-captiveportal
10.45.12.1	connectivitycheck.gstatic.com #MUDPI-captiveportal
10.45.12.1	play.googleapis.com #MUDPI-captiveportal
```

I get the idea of re-routing the requests to Google, but what is supposed to be behind 10.45.12.1 ? And what would generate requests to *.google.com ?

**Comment by olixr** [comment]
This is set to capture these request and reroute them locally for the hostspot / captive portal. Basically it enables that when the hotspot is on and you connect to it with your device, it will then auto pull up the web page dashboard. This is the same as when you connect to a guest network and it then auto pulls up that web browser page asking you to agree to some TOS. Instead MudPi uses this to pop the dashboard up without you needing to manually navigate and type the correct IP in. 

For reference I believe I used this post to help when I was designing the captive portal :https://unix.stackexchange.com/questions/432190/why-isnt-androids-captive-portal-detection-triggering-a-browser-window

**Comment by SecT0uch** [comment]
Wow okay! I see precisely what you are talking about.
I didn't know it was done that way.

Thanks for the info :)
